version: "3.7"

services:
  app0:
    container_name: b2w_pokemon_dev0
    image: b2wpokemon_dev/app:1.0
    build:
      context: ./app
      dockerfile: ./dockerfile
    working_dir: /home/node/app
    restart: always
    env_file:
      - ./.env
    environment:
      - REACT_APP_POKEMON_THEME=ghost
    ports:
      - ${APP_HOST0}:${APP_CONTAINER}
    volumes:
      - ./app:/home/node/app
    stdin_open: true
    command: "yarn start"

  app1:
    container_name: b2w_pokemon_dev1
    image: b2wpokemon_dev/app:1.0
    build:
      context: ./app
      dockerfile: ./dockerfile
    working_dir: /home/node/app
    restart: always
    env_file:
      - ./.env
    environment:
      - REACT_APP_POKEMON_THEME=water
    ports:
      - ${APP_HOST1}:${APP_CONTAINER}
    volumes:
      - ./app:/home/node/app
    stdin_open: true
    command: "yarn start"

  app2:
    container_name: b2w_pokemon_dev2
    image: b2wpokemon_dev/app:1.0
    build:
      context: ./app
      dockerfile: ./dockerfile
    working_dir: /home/node/app
    restart: always
    env_file:
      - ./.env
    environment:
      - REACT_APP_POKEMON_THEME=fire
    ports:
      - ${APP_HOST2}:${APP_CONTAINER}
    volumes:
      - ./app:/home/node/app
    stdin_open: true
    command: "yarn start"

volumes:
  app0:
  app1:
  app2:
